title: "Geongyu Lee Resume"
name: "Geongyu Lee"
description: "AI Researcher Resume Site"

remote_theme: sproogen/modern-resume-theme

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Required for modern-resume-theme
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

# Dummy content so theme can load
content:
  - title: "About"
    layout: text
    content: |
      This is a resume site for Geongyu Lee.
