name: "Geongyu Lee"
title: "AI Researcher Resume"
description: "Resume of Geongyu Lee"

remote_theme: sproogen/modern-resume-theme

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

markdown: kramdown

about_profile_image: "assets/images/profile.jpg"

content:
  - title: "About Me"
    layout: text
    content: |
      AI Researcher specializing in computational pathology and multi-omics modeling.

